create table actions (id  bigserial not null, description varchar(255) not null, type int4 not null, primary key (id));
create table actions_rule (action_id int8 not null, rule_id int8 not null, action_specification varchar(255) not null, primary key (action_id, rule_id));
create table device_features (device_id int8 not null, features_id int8 not null, specification varchar(255) not null, primary key (device_id, features_id));
create table device_template (id  bigserial not null, brand varchar(255) not null, image varchar(255) not null, model varchar(255) not null, power_supply varchar(255), release_year int4, type varchar(255) not null, primary key (id));
create table features (id  bigserial not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table home (id  bigserial not null, addressa varchar(255), city varchar(255), country varchar(255), name varchar(255), primary key (id));
create table local_device (uuid varchar(255) not null, description varchar(255) not null, supported_device_id int8 not null, location_id int8 not null, primary key (uuid));
create table location (id  bigserial not null, name varchar(255), home_id int8, primary key (id));
create table rules (id  bigserial not null, active boolean, conditions varchar(2000), description varchar(255), name varchar(255), primary key (id));
create table telegram_activation (id  bigserial not null, expiry_date timestamp, token varchar(255), telegram_user_id int8, primary key (id));
create table telegram_user (id  bigserial not null, chat_id varchar(255), enabled boolean, username varchar(255), primary key (id));
create table user_home (home_id int8 not null, user_id int8 not null);
create table users (id  bigserial not null, email varchar(255) not null, enabled boolean default false, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, secret varchar(255) not null, telegram_user_id int8, primary key (id));
create table verification_token (id  bigserial not null, expiry_date timestamp, token varchar(255), user_id int8, primary key (id));
alter table telegram_activation add constraint UK_lvrvf63g1jf9rifcy5dvmeam4 unique (telegram_user_id);
alter table telegram_user add constraint UK_8fjrx8y7kifvm13xif72sy5bf unique (chat_id);
alter table telegram_user add constraint UK_c7f0a9nq5qaaquhoyswh9pn5 unique (username);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table actions_rule add constraint FKdrnem74m95bpp2s23adqb7u0a foreign key (rule_id) references rules;
alter table actions_rule add constraint FKkbdxmu5bsutxkvor7stne0wbb foreign key (action_id) references actions;
alter table device_features add constraint FK7uivhprva3mke1uvk59m42r0a foreign key (device_id) references device_template;
alter table device_features add constraint FKcjsjodj6lwm8tldpiaflvjkns foreign key (features_id) references features;
alter table local_device add constraint FKlnc4rmqppjpxf8lhqglwi9gjm foreign key (supported_device_id) references device_template;
alter table local_device add constraint FK7rpxlg1mxbilymldv41omxywi foreign key (location_id) references location;
alter table location add constraint FKqvj3evkkjc33etbi5ksb6u748 foreign key (home_id) references home;
alter table telegram_activation add constraint FK99uknxmxl16atbsfvs1ql7s42 foreign key (telegram_user_id) references telegram_user;
alter table user_home add constraint FKo8lycc0bd4as3hocqeprxhrsw foreign key (user_id) references users;
alter table user_home add constraint FKecghr2udqlel8f11r5i373kqn foreign key (home_id) references home;
alter table users add constraint FK6qmcs8aibbq2gq6k7dr86o543 foreign key (telegram_user_id) references telegram_user;
alter table verification_token add constraint FK3asw9wnv76uxu3kr1ekq4i1ld foreign key (user_id) references users;
